// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obwafmzajwilticnaxwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9id2FmbXphandpbHRpY25heHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTg5NTIsImV4cCI6MjA2NDg5NDk1Mn0.fPZOlqigv2LuxhkmPvww9Qe7ccGMIbEKNsgme-KbAH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);